import pytest
import numpy as np

from cosapp.drivers.utils import dealias_problem
from cosapp.base import System
from cosapp.core import MathematicalProblem
from cosapp.utils.testing import get_args


@pytest.fixture
def MockUpFactory(DummySystemFactory):
    def Factory(classname="MockUp", **options):
        """`options` includes equations, unknowns, targets, etc."""
        return DummySystemFactory(
            classname,
            inwards=[
                get_args('x', 1.0),
                get_args('u', np.ones(3)),
            ],
            outwards=[
                get_args('y', 0.0),
                get_args('v', np.zeros(3)),
            ],
            **options,
        )
    return Factory


@pytest.fixture
def dummy(MockUpFactory):
    """Create simple system of type `Dummy`, generated by `MockUpFactory`.
    """
    Dummy = MockUpFactory(classname="Dummy")
    return Dummy('dummy')


@pytest.fixture
def CompositeFactory(MockUpFactory):
    """Composite system `top/mid/sub`, where `sub` is of type `MockUp`.
    """
    def Factory(**options):
        MockUp = MockUpFactory(**options)
        top = System('top')
        mid = System('mid')
        sub = mid.add_child(MockUp('sub'), pulling={'x': 'a', 'y': 'b', 'u': 'Um'})
        top.add_child(mid, pulling={'Um': 'U'})
        return top
    
    return Factory


@pytest.fixture
def top(CompositeFactory) -> System:
    """Composite system from `CompositeFactory`.
    """
    return CompositeFactory()


@pytest.fixture
def top_offdesign(CompositeFactory) -> System:
    """Composite system `top/mid/sub` from `CompositeFactory`,
    where `sub` has off-design unknowns and equations.
    """
    return CompositeFactory(
        unknowns=["x", "u"],
        equations=[
            "y == 0",
            "v == 0",
        ],
    )


def test_dealias_problem_1(top: System):
    """Test function `dealias_problem` with composite system `top`
    """
    # Create mathematical problem to be filtered
    problem = MathematicalProblem('problem', top)
    problem.add_unknown(['mid.sub.x', 'mid.sub.u'])
    problem.add_equation([
        'mid.b == 0',
        'mid.sub.y == 0',
    ])
    assert set(problem.unknowns) == {
        'mid.sub.x',
        'mid.sub.u',
    }
    assert set(problem.residues) == {
        'mid.b == 0',
        'mid.sub.y == 0',
    }

    filtered = dealias_problem(problem)
    assert set(filtered.unknowns) == {
        'U',
        'mid.a',
    }
    assert set(filtered.residues) == {
        'mid.b == 0',
        'mid.sub.y == 0',
    }


def test_dealias_problem_2(top_offdesign: System):
    """Test function `dealias_problem` with composite system `top`
    """
    top = top_offdesign  # alias
    problem = top.assembled_problem()
    filtered = dealias_problem(problem)
    assert set(filtered.unknowns) == {
        'U',
        'mid.a',
    }
    assert set(filtered.residues) == {
        'mid.sub: y == 0',
        'mid.sub: v == 0',
    }
